### ISSUE TITLE
Interact Not Working As Expected

### ISSUE THREAD

**Issue by Vanguard08** [YetiBots/Warcraft#82] opened 2016-11-22 21:15 UTC
Just installed and assigned the proper fishing (which works it casts fine).  I set Yeti to use the 9 key and went into interface / Keybindings and set 'Interact with Mouseover' to 9.

It clicks the bobber at the right time, but does not go into my bags.  Just fishes again.

Any help would be great. (yes, I tried other keys before I made this post).

**Comment by YetiBots** [comment] 2017-01-23 00:31
Duplicate of #77 but thanks for your post.

**Closed by YetiBots** 2017-01-23 00:31 UTC
Labels: Duplicate
